services:
  postgres:
    image: postgres:16
    container_name: tms-postgres
    environment:
      POSTGRES_DB: tmsdb
      POSTGRES_USER: tmsuser
      POSTGRES_PASSWORD: tmspass
    ports: ["5432:5432"]
    volumes: [pg_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tmsuser -d tmsdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  postgres-dev:
    image: postgres:16
    container_name: tms-postgres-dev
    environment:
      POSTGRES_DB: tmsdb_dev
      POSTGRES_USER: tmsuser
      POSTGRES_PASSWORD: tmspass
    ports: ["5433:5432"]
    volumes: [pg_data_dev:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tmsuser -d tmsdb_dev"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: tms-redis
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    volumes:
      - tms_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pg_data:
  pg_data_dev:
  tms_redis_data:
