spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tmsdb
    username: tmsuser
    password: tmspass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # 建表交给 Flyway；先跑通可改为 none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  logging.level:
    org.hibernate.SQL: debug
