spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tmsdb
    username: tmsuser
    password: tmspass
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 30000

  # Flyway manages schema in prod
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    # clean-disabled: true   # keep true in real production to prevent accidental clean

  # schema managed by Flyway; do not run Spring SQL init in prod
  sql:
    init:
      mode: never

  data:
    redis:
      host: localhost
      port: 6379
      # 密码本地可以不配，线上再加密码 + 环境变量
      # password: ${TMS_REDIS_PASSWORD:}
      database: 1              # ⚠️ 用 1，和 dev 的 db=0 做环境隔离

  cache:
    type: redis
    redis:
      time-to-live: 600000

  # Kafka prod
  kafka:
    bootstrap-servers: localhost:9092
    # real prod env
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    consumer:
      # prod 下你也可以不给默认 group-id，让每个 @KafkaListener 自己指定
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.example.kafka.event"
        spring.json.use.type.headers: false
      # prod 一般用 latest；你可以按需要改，这里先不设就用默认
      # auto-offset-reset: latest

    listener:
      ack-mode: record

server:
  port: 8080

jwt:
  secret: "change-this-very-long-secret-please-make-it-longer-32bytes-minimum"
  ttl-minutes: 60

logging:
  level:
    org.springframework.security: DEBUG
    org.flywaydb: INFO
